### ISSUE TITLE
`npm audit` suggests several version bumps

### ISSUE THREAD

**Issue by tkoeppe** [chrishayesmu/XCOM-Companion#1]
When running `npm install` on Linux, I get a recommendation to run `npm audit` to address known security vulnerabilities in various dependencies. Can you repro/fix that? Would you perhaps like a pull request?

**Comment by chrishayesmu** [comment]
I do get those warnings on Windows as well, but since all of the vulnerabilities relate to running untrusted content, and XCOM Companion loads zero remote files, I haven't bothered to fix them. You're welcome to submit a PR if you want, though.

**Comment by tkoeppe** [comment]
Sure, can do. Yes, I see what you mean, I just thought it'd be nice to minimize warnings.

**Comment by chrishayesmu** [comment]
Both PRs look good, merged them. Thanks! I'd like to credit you in the next patch notes - is that okay, and if so, how would you like to be credited?

As an aside, has XCOM Companion run okay on Linux?

**Comment by tkoeppe** [comment]
Oh, thank you, but don't worry! This was just some auto-generated change. We can get to that if I have something substantial to add!

Yes, it works perfectly on Linux, thanks! That is, I just use `npm start`, as you describe; there's no "self-contained version". But that seems ideal anyway.

**Comment by chrishayesmu** [comment]
Well I'm a big believer in no work going unrecognized, even if it's just testing an automated change, so let me know if you change your mind. I'll be mentioning the change in the notes either way, just a question of whether it's anonymous. (I also just think it's really cool someone wanted to contribute! 😁)

**Comment by tkoeppe** [comment]
Appreciated :-) Anonymous is fine for now; people can look up the git commit history anyway!
