### ISSUE TITLE
Build Manager:  Selecting Extra Conditioning on a Goliath breaks stats preview

### ISSUE THREAD

**Issue by elmacsee** [chrishayesmu/XCOM-Companion#11]
When creating a loadout for a Goliath; the stats preview on the right with aim, mobility, perks, etc disappears after selecting the Extra Conditioning perk.
It is no longer visible within the loadout or the saved loadouts list.
The saved loadouts list will instead show either nothing, or the stats preview of the previous loadout you selected in the list.

Equipment doesn't seem to matter and no other perks at the MSGT level cause the issue, just extra conditioning (screenshot below shows Rapid Fire selected as example).
![with Rapid Fire](https://user-images.githubusercontent.com/88979660/129484880-c5bd071d-dc12-47f6-8993-caa1db1375d8.JPG)
![With Extra Con](https://user-images.githubusercontent.com/88979660/129484883-bf087b96-9f21-4a76-be00-3867942aa51f.JPG)

Goliath too tanky for companion I guess

**Comment by chrishayesmu** [comment]
Goliath contained too much raw power for Companion to handle, but following https://github.com/chrishayesmu/XCOM-Companion/commit/1bda3e043dea453fb52208906f649a49a19c831f, it can be contained safely. Thanks for the report!
