### ISSUE TITLE
Elerium Generator costs

### ISSUE THREAD

**Issue by elmacsee** [chrishayesmu/XCOM-Companion#12]
The $ value of the Elerium Generator is too cheap on the app.
Base build is $400 rather than the $200 on the app.
Rush build is $600 rather than $300

Meld Alloy and Elerium counts all seem correct though
![Elerium](https://user-images.githubusercontent.com/88979660/129592943-44ccb2f9-4fb3-4a9d-a70f-eb43719a1b9c.JPG)

**Comment by chrishayesmu** [comment]
Whoops! Another good catch, thanks. Corrected in https://github.com/chrishayesmu/XCOM-Companion/commit/75e7a080ae7049ac10348d6877784bc2da3ff4ff. I reviewed other base facilities and didn't see any discrepancies, but please let me know if you see anything else.

I don't mind if you prefer to just ping me on Discord by the way, whatever's easier for you.
