### ISSUE TITLE
Gauss research missing icon

### ISSUE THREAD

**Issue by elmacsee** [chrishayesmu/XCOM-Companion#13]
I could swear this was visible before, could potentially be a local client issue on my machine.
![Gauss](https://user-images.githubusercontent.com/88979660/129601254-1652c328-a990-450a-8c80-d2d5c97f3797.JPG)

**Comment by chrishayesmu** [comment]
Well this is super weird. Gauss Weapons is the only image filename where the name was accidentally capitalized, and for some reason that's okay in development builds, but doesn't seem to be in release. That is very obnoxious behavior.

I've hopefully fixed it but I'll leave this open until I do the next release and confirm.

**Comment by chrishayesmu** [comment]
Resolved in v0.7.6.
