### ISSUE TITLE
Feature request: country starting & satellite bonuses

### ISSUE THREAD

**Issue by diego-andersen** [chrishayesmu/XCOM-Companion#15]
Hi! Would like to request an addition to the development roadmap: a complete list of country starting and mid-campaign satellite bonuses, which would help in the campaign plan.

A number of countries have different bonuses depending on whether you start there or launch a satellite over them later, and it would be useful in the upcoming campaign planning tool to be able to compare these at a glance. Continent bonuses would be welcome too, but those are easier to remember.

Thanks for all the hard work!

**Comment by chrishayesmu** [comment]
Hi, sorry I didn't respond to this before! Companion development is on hiatus at the moment while I focus on other projects, and it completely slipped my mind.

Love the suggestion, and will definitely roll that into the eventual campaign planner if I do return to Companion development in the future.

**Comment by chrishayesmu** [comment]
All of this information is now available in the new Campaign Planner tool, when creating a new campaign. It's not as convenient as a dedicated page for it, but hopefully that helps. I'm unlikely to return to this project for long enough to add something dedicated to country/continent bonuses, unfortunately.
