### ISSUE TITLE
UFO grouping by size

### ISSUE THREAD

**Issue by TheaKersh** [chrishayesmu/XCOM-Companion#16]
This is relatively subjective, but I think it might be a good idea to group UFO classes by size in the UFO screen. I feel like this might make it slightly easier to navigate. 
Like so
Small -
  Scout
  Fighter
Medium -
  Raider
  Destroyer
  Overseer
Large -
  Abductor
  Terror Ship
  Transport
  Harvester
Very Large -
  Battleship
  Assault Carrier

(the above being an example of how the ufos would be grouped, not necessarily a suggestion as to the actual layout)

**Comment by chrishayesmu** [comment]
Thanks for the suggestion! XCOM Companion isn't in active development right now, but I agree that this would be a good idea. Most people checking the UFO listing are probably staring at an unknown UFO in-game, and the main thing they know is the size. I'll keep this in mind if/when I return to this project.
